// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Bearcam
{
	public partial class WebcamCell : UICollectionViewCell
	{
		public WebcamCell (IntPtr handle) : base (handle)
		{
		}

        public UIImageView GetThumbnail ()
        {
            return this.Thumbnail;
        }

        public NSUrl Url { get; set; }

        public override void DidUpdateFocus (UIFocusUpdateContext context, UIFocusAnimationCoordinator coordinator)
        {
            coordinator.AddCoordinatedAnimations (() =>
            {
                if (this.Focused)
                {
                    this.Title.Alpha = 1.0f;
                }
                else
                {
                    this.Title.Alpha = 0.0f;
                }
            }, null);
        }
	}
}
